name: Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: Run CI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
          cache: yarn
      - run: yarn
      - run: yarn lint && yarn typescript && yarn test
